In [1]:
include("./src/Layers.jl")
using .Layers
Layers.greet()


Hello World!

In [2]:
# Input = zeros(Float64, 1,2)
Input = [0.5, 0.7]'

dense1 = Dense(2,2)
InitLayer!(dense1, Input)

DisplayLayer(dense1)
 

"Dense layer"

1×2 Matrix{Float64}:
 0.5  0.7

2×2 Matrix{Float64}:
  0.663547  -0.0200682
 -0.263895   0.224598

1×2 Matrix{Float64}:
 0.200542  0.0724864

1×2 Matrix{Float64}:
 0.0  0.0

In [3]:
dense2 = Dense(2,4)
InitLayer!(dense2, dense1)

DisplayLayer(dense2)

Dense

"Dense layer"

1×2 Matrix{Float64}:
 0.0  0.0

2×4 Matrix{Float64}:
 0.994921  2.26369    0.753084  -0.56772
 0.397561  0.405266  -1.16581   -0.71127

1×4 Matrix{Float64}:
 -1.44906  -0.645621  -1.16525  -0.153167

1×4 Matrix{Float64}:
 0.0  0.0  0.0  0.0

In [4]:
CalcOutputResursive!(dense1)

In [5]:
DisplayNetwork(dense1)

"Dense layer"

1×2 Matrix{Float64}:
 0.5  0.7

2×2 Matrix{Float64}:
  0.663547  -0.0200682
 -0.263895   0.224598

1×2 Matrix{Float64}:
 0.200542  0.0724864

1×2 Matrix{Float64}:
 0.347589  0.219671

"Dense layer"

1×2 Matrix{Float64}:
 0.347589  0.219671

2×4 Matrix{Float64}:
 0.994921  2.26369    0.753084  -0.56772
 0.397561  0.405266  -1.16581   -0.71127

1×4 Matrix{Float64}:
 -1.44906  -0.645621  -1.16525  -0.153167

1×4 Matrix{Float64}:
 0.0  0.230238  0.0  0.0

In [6]:
DisplayShortNetwork(dense1)

"Dense layer"

1×2 Matrix{Float64}:
 0.5  0.7

1×2 Matrix{Float64}:
 0.347589  0.219671

"Dense layer"

1×2 Matrix{Float64}:
 0.347589  0.219671

1×4 Matrix{Float64}:
 0.0  0.230238  0.0  0.0