In [1]:
include("./src/Layers.jl")
include("./src/Dense.jl")
# using .DenseModule
# using .Layers
# greet()


DisplayShortLayer (generic function with 2 methods)

In [2]:
# Input = zeros(Float64, 1,2)
Input = [0.5, 0.7]'

dense1 = Dense(2,2)
InitLayer!(dense1, Input)

DisplayLayer(dense1)
 

"Dense layer"

1×2 Matrix{Float64}:
 0.5  0.7

2×2 Matrix{Float64}:
 -0.107629  0.413495
  0.110228  0.153848

1×2 Matrix{Float64}:
 0.57876  -1.45265

1×2 Matrix{Float64}:
 0.0  0.0

In [3]:
dense2 = Dense(2,4)
InitLayer!(dense2, dense1)

DisplayLayer(dense2)

Dense

"Dense layer"

1×2 Matrix{Float64}:
 0.0  0.0

2×4 Matrix{Float64}:
 -1.1172    -0.0952444  -0.31355  -0.538654
  0.256111   0.993873    0.4893    1.12593

1×4 Matrix{Float64}:
 -0.18228  -0.617105  -3.14359  0.0127548

1×4 Matrix{Float64}:
 0.0  0.0  0.0  0.0

In [4]:
CalcOutputResursive!(dense1)

In [5]:
DisplayNetwork(dense1)

"Dense layer"

1×2 Matrix{Float64}:
 0.5  0.7

2×2 Matrix{Float64}:
 -0.107629  0.413495
  0.110228  0.153848

1×2 Matrix{Float64}:
 0.57876  -1.45265

1×2 Matrix{Float64}:
 0.602105  0.0

"Dense layer"

1×2 Matrix{Float64}:
 0.602105  0.0

2×4 Matrix{Float64}:
 -1.1172    -0.0952444  -0.31355  -0.538654
  0.256111   0.993873    0.4893    1.12593

1×4 Matrix{Float64}:
 -0.18228  -0.617105  -3.14359  0.0127548

1×4 Matrix{Float64}:
 0.0  0.0  0.0  0.0

In [6]:
DisplayShortNetwork(dense1)

"Dense layer"

1×2 Matrix{Float64}:
 0.5  0.7

1×2 Matrix{Float64}:
 0.602105  0.0

"Dense layer"

1×2 Matrix{Float64}:
 0.602105  0.0

1×4 Matrix{Float64}:
 0.0  0.0  0.0  0.0